import type { Metadata } from "next";
import "@/app/styles/globals.css";
import {Providers} from "@/app/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="es">
        <body
            // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            className={""}
        >
        <Providers>
            {/*Contenedor Main*/}

            {children}

        </Providers>
        </body>
        </html>
    );
}
