services:
  next-front:
    build:
      context: ./next-front
    ports:
      - "3000:3000"
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
  product-services:
    build:
      context: ./spring-backend/services/product-services
    ports:
      - "8080:8080"
    restart: unless-stopped
    init: true
networks:
  default:
    name: project-network