version: '3.9'
services:
  frontend:
    build:
      context: ./next-front
    ports:
      - "3000:3000"
    networks:
      - app-network
  backend:
    build:
      context: ./spring-backend/services/product-services
    ports:
      - "8081:8081"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
