services:
  ms-customers-db:
    image: postgres:17
    container_name: ms-customers-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-customers-db
    ports:
      - "5439:5432"
    networks:
      - backend

  ms-orders-db:
    image: postgres:17
    container_name: ms-orders-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-orders-db
    ports:
      - "5440:5432"
    networks:
      - backend


  ms-products-db:
    image: postgres:17
    container_name: ms-products-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-products-db
    ports:
      - "5441:5432"
    networks:
      - backend


networks:
  backend:
    driver: bridge