services:
  customers-db:
    image: postgres:15
    container_name: customers-db
    restart: always
    environment:
      POSTGRES_DB: ms_customers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/init/create_tables_customers.sql:/docker-entrypoint-initdb.d/create_tables_customers.sql

volumes:
  customers-data:
