import { Customer } from "@/types/customer";

export const mockCustomers: Customer[] = [
    {
        customerId: 1024,
        companyName: "AutoMotores Del Sur S.A.",
        companyType: "Distribuidora Automotriz",
        contactLastName: "Pérez",
        contactFirstName: "Juan",
        contactRole: "Director Comercial",
        phone: "+54 11 4321-5678",
        city: "Monterrey",
        country: "NL",
        creditLimit: 45000,
        status: "Active",
    },
    {
        customerId: 1025,
        companyName: "Talleres Rapidos MX",
        companyType: "Taller Mecánico",
        contactLastName: "López",
        contactFirstName: "Ana",
        contactRole: "Gerente",
        phone: "+52 33 1234-5678",
        city: "Guadalajara",
        country: "JAL",
        creditLimit: 12500,
        status: "Active",
    },
    {
        customerId: 1026,
        companyName: "Refaccionaria El Rayo",
        companyType: "Retail",
        contactLastName: "Ruiz",
        contactFirstName: "Carlos",
        contactRole: null,
        phone: "+52 55 9876-5432",
        city: "CDMX",
        country: "Centro",
        creditLimit: 8900,
        status: "Inactive",
    },
    {
        customerId: 1027,
        companyName: "Transportes Logísticos",
        companyType: "Flota Corporativa",
        contactLastName: "Martínez",
        contactFirstName: "Sofía",
        contactRole: "Jefa de Compras",
        phone: "+52 442 123-4567",
        city: "Querétaro",
        country: "QRO",
        creditLimit: 150000,
        status: "Pending",
    },
    {
        customerId: 1028,
        companyName: "Servicios Automotrices V.",
        companyType: "Taller Especializado",
        contactLastName: "Vega",
        contactFirstName: "Luis",
        contactRole: "Gerente",
        phone: "+52 222 567-8901",
        city: "Puebla",
        country: "PUE",
        creditLimit: 21000,
        status: "Active",
    },
    {
        customerId: 1029,
        companyName: "AutoParts Buenos Aires",
        companyType: "Importadora",
        contactLastName: "González",
        contactFirstName: "Roberto",
        contactRole: "Director General",
        phone: "+54 11 4321-5678",
        city: "Buenos Aires",
        country: "ARG",
        creditLimit: 50000,
        status: "Active",
    },
    {
        customerId: 1030,
        companyName: "Repuestos del Sur",
        companyType: "Distribuidora",
        contactLastName: "Martínez",
        contactFirstName: "Laura",
        contactRole: "Gerente de Ventas",
        phone: "+54 351 432-1234",
        city: "Córdoba",
        country: "ARG",
        creditLimit: 35000,
        status: "Active",
    },
    {
        customerId: 1031,
        companyName: "Motores Premium SA",
        companyType: "Fabricante",
        contactLastName: "López",
        contactFirstName: "Carlos",
        contactRole: "CEO",
        phone: "+54 341 456-7890",
        city: "Rosario",
        country: "ARG",
        creditLimit: 75000,
        status: "Active",
    },
    {
        customerId: 1032,
        companyName: "Distribuidora Norte",
        companyType: "Mayorista",
        contactLastName: "Fernández",
        contactFirstName: "Ana",
        contactRole: "Administradora",
        phone: null,
        city: "Tucumán",
        country: "ARG",
        creditLimit: 20000,
        status: "Inactive",
    },
    {
        customerId: 1033,
        companyName: "Autos & Más",
        companyType: "Concesionaria",
        contactLastName: "Rodríguez",
        contactFirstName: "Diego",
        contactRole: "Director",
        phone: "+598 2 901-2345",
        city: "Montevideo",
        country: "URY",
        creditLimit: 45000,
        status: "Active",
    },
    {
        customerId: 1034,
        companyName: "TechCar SRL",
        companyType: "Tecnología Automotriz",
        contactLastName: "Pérez",
        contactFirstName: "Sofía",
        contactRole: "CTO",
        phone: "+56 2 2345-6789",
        city: "Santiago",
        country: "CHL",
        creditLimit: 60000,
        status: "Pending",
    },
    {
        customerId: 1035,
        companyName: "Importadora Central",
        companyType: "Importadora",
        contactLastName: "García",
        contactFirstName: "Martín",
        contactRole: null,
        phone: "+54 261 432-5678",
        city: "Mendoza",
        country: "ARG",
        creditLimit: null,
        status: "Inactive",
    },
    {
        customerId: 1036,
        companyName: "MegaAuto Paraguay",
        companyType: "Concesionaria",
        contactLastName: "Benítez",
        contactFirstName: "Juan",
        contactRole: "Gerente General",
        phone: "+595 21 345-6789",
        city: "Asunción",
        country: "PRY",
        creditLimit: 30000,
        status: "Active",
    },
    {
        customerId: 1037,
        companyName: "Recambios Express",
        companyType: "E-commerce",
        contactLastName: "Sánchez",
        contactFirstName: "María",
        contactRole: "Directora de Operaciones",
        phone: "+54 11 5678-1234",
        city: "Buenos Aires",
        country: "ARG",
        creditLimit: 15000,
        status: "Active",
    },
    {
        customerId: 1038,
        companyName: "Automotriz del Litoral",
        companyType: "Taller Mecánico",
        contactLastName: "Ramírez",
        contactFirstName: "Pedro",
        contactRole: "Propietario",
        phone: "+54 342 456-7890",
        city: "Santa Fe",
        country: "ARG",
        creditLimit: 25000,
        status: "Active",
    },
    {
        customerId: 1039,
        companyName: "Frenos & Embragues SA",
        companyType: "Fabricante",
        contactLastName: "Torres",
        contactFirstName: "Valentina",
        contactRole: "Gerente de Planta",
        phone: "+54 381 234-5678",
        city: "Tucumán",
        country: "ARG",
        creditLimit: 40000,
        status: "Active",
    },
    {
        customerId: 1040,
        companyName: "Lubricantes Pro",
        companyType: "Distribuidor",
        contactLastName: "Díaz",
        contactFirstName: "Facundo",
        contactRole: null,
        phone: null,
        city: "La Plata",
        country: "ARG",
        creditLimit: 18000,
        status: "Inactive",
    },
    {
        customerId: 1041,
        companyName: "PartsWorld Bolivia",
        companyType: "Importadora",
        contactLastName: "Morales",
        contactFirstName: "Gabriela",
        contactRole: "Gerente Comercial",
        phone: "+591 2 234-5678",
        city: "La Paz",
        country: "BOL",
        creditLimit: 22000,
        status: "Active",
    },
    {
        customerId: 1042,
        companyName: "Repuestos Originales",
        companyType: "Retail Premium",
        contactLastName: "Acosta",
        contactFirstName: "Lucas",
        contactRole: "Jefe de Compras",
        phone: "+54 299 456-7890",
        city: "Neuquén",
        country: "ARG",
        creditLimit: 55000,
        status: "Pending",
    },
    {
        customerId: 1043,
        companyName: "Automotores del Este",
        companyType: "Concesionaria",
        contactLastName: "Herrera",
        contactFirstName: "Camila",
        contactRole: "Directora",
        phone: "+55 11 9876-5432",
        city: "São Paulo",
        country: "BRA",
        creditLimit: 80000,
        status: "Active",
    },
    {
        customerId: 1044,
        companyName: "Taller Los Hermanos",
        companyType: "Taller Mecánico",
        contactLastName: "Méndez",
        contactFirstName: "Emilio",
        contactRole: "Co-propietario",
        phone: "+54 2944 34-5678",
        city: "Bariloche",
        country: "ARG",
        creditLimit: 12000,
        status: "Inactive",
    },
    {
        customerId: 1045,
        companyName: "Industrial Cars SAS",
        companyType: "Flota Corporativa",
        contactLastName: "Vargas",
        contactFirstName: "Natalia",
        contactRole: "Gerente de Logística",
        phone: "+57 1 234-5678",
        city: "Bogotá",
        country: "COL",
        creditLimit: 65000,
        status: "Active",
    },
    {
        customerId: 1046,
        companyName: "Tren Motriz SA",
        companyType: "Fabricante",
        contactLastName: "Castro",
        contactFirstName: "Ignacio",
        contactRole: "Director Técnico",
        phone: "+54 223 456-7890",
        city: "Mar del Plata",
        country: "ARG",
        creditLimit: 28000,
        status: "Active",
    },
    {
        customerId: 1047,
        companyName: "Autopiezas Lima",
        companyType: "Distribuidora",
        contactLastName: "Quispe",
        contactFirstName: "Rosa",
        contactRole: "Gerente",
        phone: "+51 1 234-5678",
        city: "Lima",
        country: "PER",
        creditLimit: 33000,
        status: "Active",
    },
    {
        customerId: 1048,
        companyName: "Suspensiones Max",
        companyType: "Especialista",
        contactLastName: "Romero",
        contactFirstName: "Alejandro",
        contactRole: null,
        phone: "+54 11 3456-7890",
        city: "Buenos Aires",
        country: "ARG",
        creditLimit: null,
        status: "Inactive",
    },
];
