import { Customer } from "@/types/customer";

export const mockCustomers: Customer[] = [
    {
        customerNumber: 112,
        customerName: "Cliente Demo EPC-02",
        contactLastName: "Testing",
        contactFirstName: "User",
        phone: "+54 11 4000-0112",
        city: "Buenos Aires",
        country: "ARG",
        creditLimit: 30000,
        status: "Active",
    },
    {
        customerNumber: 1024,
        customerName: "AutoMotores Del Sur S.A.",
        contactLastName: "Pérez",
        contactFirstName: "Juan",
        phone: "+54 11 4321-5678",
        city: "Monterrey",
        country: "NL",
        creditLimit: 45000,
        status: "Active",
    },
    {
        customerNumber: 1025,
        customerName: "Talleres Rapidos MX",
        contactLastName: "López",
        contactFirstName: "Ana",
        phone: "+52 33 1234-5678",
        city: "Guadalajara",
        country: "JAL",
        creditLimit: 12500,
        status: "Active",
    },
    {
        customerNumber: 1026,
        customerName: "Refaccionaria El Rayo",
        contactLastName: "Ruiz",
        contactFirstName: "Carlos",
        phone: "+52 55 9876-5432",
        city: "CDMX",
        country: "Centro",
        creditLimit: 8900,
        status: "Inactive",
    },
    {
        customerNumber: 1027,
        customerName: "Transportes Logísticos",
        contactLastName: "Martínez",
        contactFirstName: "Sofía",
        phone: "+52 442 123-4567",
        city: "Querétaro",
        country: "QRO",
        creditLimit: 150000,
        status: "Pending",
    },
    {
        customerNumber: 1028,
        customerName: "Servicios Automotrices V.",
        contactLastName: "Vega",
        contactFirstName: "Luis",
        phone: "+52 222 567-8901",
        city: "Puebla",
        country: "PUE",
        creditLimit: 21000,
        status: "Active",
    },
    {
        customerNumber: 1029,
        customerName: "AutoParts Buenos Aires",
        contactLastName: "González",
        contactFirstName: "Roberto",
        phone: "+54 11 4321-5678",
        city: "Buenos Aires",
        country: "ARG",
        creditLimit: 50000,
        status: "Active",
    },
    {
        customerNumber: 1030,
        customerName: "Repuestos del Sur",
        contactLastName: "Martínez",
        contactFirstName: "Laura",
        phone: "+54 351 432-1234",
        city: "Córdoba",
        country: "ARG",
        creditLimit: 35000,
        status: "Active",
    },
    {
        customerNumber: 1031,
        customerName: "Motores Premium SA",
        contactLastName: "López",
        contactFirstName: "Carlos",
        phone: "+54 341 456-7890",
        city: "Rosario",
        country: "ARG",
        creditLimit: 75000,
        status: "Active",
    },
    {
        customerNumber: 1032,
        customerName: "Distribuidora Norte",
        contactLastName: "Fernández",
        contactFirstName: "Ana",
        phone: null,
        city: "Tucumán",
        country: "ARG",
        creditLimit: 20000,
        status: "Inactive",
    },
    {
        customerNumber: 1033,
        customerName: "Autos & Más",
        contactLastName: "Rodríguez",
        contactFirstName: "Diego",
        phone: "+598 2 901-2345",
        city: "Montevideo",
        country: "URY",
        creditLimit: 45000,
        status: "Active",
    },
    {
        customerNumber: 1034,
        customerName: "TechCar SRL",
        contactLastName: "Pérez",
        contactFirstName: "Sofía",
        phone: "+56 2 2345-6789",
        city: "Santiago",
        country: "CHL",
        creditLimit: 60000,
        status: "Pending",
    },
    {
        customerNumber: 1035,
        customerName: "Importadora Central",
        contactLastName: "García",
        contactFirstName: "Martín",
        phone: "+54 261 432-5678",
        city: "Mendoza",
        country: "ARG",
        creditLimit: null,
        status: "Inactive",
    },
    {
        customerNumber: 1036,
        customerName: "MegaAuto Paraguay",
        contactLastName: "Benítez",
        contactFirstName: "Juan",
        phone: "+595 21 345-6789",
        city: "Asunción",
        country: "PRY",
        creditLimit: 30000,
        status: "Active",
    },
    {
        customerNumber: 1037,
        customerName: "Recambios Express",
        contactLastName: "Sánchez",
        contactFirstName: "María",
        phone: "+54 11 5678-1234",
        city: "Buenos Aires",
        country: "ARG",
        creditLimit: 15000,
        status: "Active",
    },
    {
        customerNumber: 1038,
        customerName: "Automotriz del Litoral",
        contactLastName: "Ramírez",
        contactFirstName: "Pedro",
        phone: "+54 342 456-7890",
        city: "Santa Fe",
        country: "ARG",
        creditLimit: 25000,
        status: "Active",
    },
    {
        customerNumber: 1039,
        customerName: "Frenos & Embragues SA",
        contactLastName: "Torres",
        contactFirstName: "Valentina",
        phone: "+54 381 234-5678",
        city: "Tucumán",
        country: "ARG",
        creditLimit: 40000,
        status: "Active",
    },
    {
        customerNumber: 1040,
        customerName: "Lubricantes Pro",
        contactLastName: "Díaz",
        contactFirstName: "Facundo",
        phone: null,
        city: "La Plata",
        country: "ARG",
        creditLimit: 18000,
        status: "Inactive",
    },
    {
        customerNumber: 1041,
        customerName: "PartsWorld Bolivia",
        contactLastName: "Morales",
        contactFirstName: "Gabriela",
        phone: "+591 2 234-5678",
        city: "La Paz",
        country: "BOL",
        creditLimit: 22000,
        status: "Active",
    },
    {
        customerNumber: 1042,
        customerName: "Repuestos Originales",
        contactLastName: "Acosta",
        contactFirstName: "Lucas",
        phone: "+54 299 456-7890",
        city: "Neuquén",
        country: "ARG",
        creditLimit: 55000,
        status: "Pending",
    },
    {
        customerNumber: 1043,
        customerName: "Automotores del Este",
        contactLastName: "Herrera",
        contactFirstName: "Camila",
        phone: "+55 11 9876-5432",
        city: "São Paulo",
        country: "BRA",
        creditLimit: 80000,
        status: "Active",
    },
    {
        customerNumber: 1044,
        customerName: "Taller Los Hermanos",
        contactLastName: "Méndez",
        contactFirstName: "Emilio",
        phone: "+54 2944 34-5678",
        city: "Bariloche",
        country: "ARG",
        creditLimit: 12000,
        status: "Inactive",
    },
    {
        customerNumber: 1045,
        customerName: "Industrial Cars SAS",
        contactLastName: "Vargas",
        contactFirstName: "Natalia",
        phone: "+57 1 234-5678",
        city: "Bogotá",
        country: "COL",
        creditLimit: 65000,
        status: "Active",
    },
    {
        customerNumber: 1046,
        customerName: "Tren Motriz SA",
        contactLastName: "Castro",
        contactFirstName: "Ignacio",
        phone: "+54 223 456-7890",
        city: "Mar del Plata",
        country: "ARG",
        creditLimit: 28000,
        status: "Active",
    },
    {
        customerNumber: 1047,
        customerName: "Autopiezas Lima",
        contactLastName: "Quispe",
        contactFirstName: "Rosa",
        phone: "+51 1 234-5678",
        city: "Lima",
        country: "PER",
        creditLimit: 33000,
        status: "Active",
    },
    {
        customerNumber: 1048,
        customerName: "Suspensiones Max",
        contactLastName: "Romero",
        contactFirstName: "Alejandro",
        phone: "+54 11 3456-7890",
        city: "Buenos Aires",
        country: "ARG",
        creditLimit: null,
        status: "Inactive",
    },
];
