# Archivo: .github/workflows/playwright-tests.yml
name: Pruebas de Playwright

# Cuándo se ejecuta el workflow
on:
  push:
    branches: [ DevOps ]  # Se ejecuta en push a main o develop
  pull_request:
    branches: [ DevOps ]           # Se ejecuta en PRs hacia main

# Configuración del job
jobs:
  test:
    # Sistema operativo donde se ejecuta
    runs-on: ubuntu-latest
    
    # Estrategia de matriz para probar en múltiples versiones
    strategy:
      matrix:
        python-version: [3.11]
        browser: [chromium, firefox]  # Probar en diferentes navegadores
    
    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout código
        uses: actions/checkout@v4
        
      # 2. Configurar Python
      - name: Configurar Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      # 3. Cache para dependencias (acelera builds)
      - name: Cache dependencias pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      # 4. Instalar dependencias de Python
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r test-automation/requirements.txt
          
      # 5. Instalar navegadores de Playwright
      - name: Instalar navegadores Playwright
        run: playwright install --with-deps
        
      # 6. Crear carpetas necesarias
      - name: Crear carpetas de reportes
        run: |
          mkdir -p reports
          mkdir -p test-results
          
      # 7. Ejecutar pruebas
      - name: Ejecutar pruebas Playwright
        run: |
          pytest test-automation/tests/ \
            --browser ${{ matrix.browser }} \
            --html=reports/playwright-report-${{ matrix.browser }}.html \
            --self-contained-html \
            --junit-xml=test-results/junit-${{ matrix.browser }}.xml

        env:
          # Variables de entorno para las pruebas
          CI: true
          
      # 8. Subir reportes HTML si fallan las pruebas
      - name: Subir reportes HTML
        uses: actions/upload-artifact@v4
        if: failure()  # Solo si las pruebas fallan
        with:
          name: playwright-reports-${{ matrix.browser }}
          path: |
            reports/
            test-results/
          retention-days: 30
          
      # 9. Subir screenshots si fallan las pruebas
      - name: Subir screenshots de errores
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots-${{ matrix.browser }}
          path: reports/screenshot_*.png
          retention-days: 7
          
      # 10. Publicar resultados de pruebas
      - name: Publicar resultados
        uses: dorny/test-reporter@v1
        if: success() || failure()  # Siempre ejecutar
        with:
          name: Resultados Playwright (${{ matrix.browser }})
          path: test-results/junit-${{ matrix.browser }}.xml
          reporter: java-junit